"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.DEFAULT_BROWSERS = exports.RUNTIME_CHUNK_NAME = exports.COMMON_CHUNK_NAME = exports.DEFAULT_DEV_SERVER_HOST = exports.DEFAULT_NODE_SERVER_DEBUG_PORT = exports.DEFAULT_DEV_SERVER_PORT = exports.DEFAULT_OUTPUT_PATH = exports.DEFAULT_PUBLIC_PATH = exports.DEFAULT_STAGE = exports.COMMANDS = exports.PROJECT_TYPES = exports.REACT_COMPONENT = exports.REACT_APP = exports.CONFIG_FILE_NAME = void 0;
const CONFIG_FILE_NAME = 'sm.config.js';
exports.CONFIG_FILE_NAME = CONFIG_FILE_NAME;
const REACT_APP = 'react-app';
exports.REACT_APP = REACT_APP;
const REACT_COMPONENT = 'react-component';
exports.REACT_COMPONENT = REACT_COMPONENT;
const PROJECT_TYPES = [REACT_APP, REACT_COMPONENT];
exports.PROJECT_TYPES = PROJECT_TYPES;
const COMMANDS = ['dev-server', 'build', 'create', 'node-server', 'build-zip'];
exports.COMMANDS = COMMANDS;
const DEFAULT_STAGE = 2;
exports.DEFAULT_STAGE = DEFAULT_STAGE;
const DEFAULT_PUBLIC_PATH = '/';
exports.DEFAULT_PUBLIC_PATH = DEFAULT_PUBLIC_PATH;
const DEFAULT_OUTPUT_PATH = 'dist';
exports.DEFAULT_OUTPUT_PATH = DEFAULT_OUTPUT_PATH;
const DEFAULT_DEV_SERVER_PORT = process.env.port || 4000;
exports.DEFAULT_DEV_SERVER_PORT = DEFAULT_DEV_SERVER_PORT;
const DEFAULT_NODE_SERVER_DEBUG_PORT = 5858;
exports.DEFAULT_NODE_SERVER_DEBUG_PORT = DEFAULT_NODE_SERVER_DEBUG_PORT;
const DEFAULT_DEV_SERVER_HOST = 'localhost';
exports.DEFAULT_DEV_SERVER_HOST = DEFAULT_DEV_SERVER_HOST;
const COMMON_CHUNK_NAME = 'common';
exports.COMMON_CHUNK_NAME = COMMON_CHUNK_NAME;
const RUNTIME_CHUNK_NAME = 'runtime';
exports.RUNTIME_CHUNK_NAME = RUNTIME_CHUNK_NAME;
const DEFAULT_BROWSERS = ["> 1%", "last 2 versions", "not ie <= 9"];
exports.DEFAULT_BROWSERS = DEFAULT_BROWSERS;